import type { ReportDocument } from "@/lib/report-document"

export function ReportDocumentView({ document }: { document: ReportDocument }) {
  return <article className="space-y-4 rounded-xl border border-border bg-background p-4">
    <header><p className="font-aldrich text-[10px] uppercase tracking-[0.18em] text-primary">AVIntelligence · Smart Storage</p><h3 className="mt-2 text-lg font-semibold">{document.title}</h3>{document.subtitle && <p className="mt-1 text-xs text-muted-foreground">{document.subtitle}</p>}</header>
    {document.coverage && <div className="rounded-lg border-l-2 border-primary bg-muted/30 px-3 py-2 text-xs text-muted-foreground"><span className="font-medium text-foreground">Coverage. </span>{document.coverage.statement}</div>}
    {document.blocks.map((block, index) => block.suppressed ? <div key={index} className="rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground"><span className="font-medium uppercase text-foreground">{block.type} — not stated. </span>{block.reason}</div> : block.type === "kpi" ? <div key={index} className="grid gap-2 sm:grid-cols-2">{block.items.map((item) => <div key={item.label} className="rounded-lg border border-border p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{item.label}</p><p className="mt-1 text-xl font-semibold">{item.value}</p>{item.note && <p className="text-[10px] text-muted-foreground">{item.note}</p>}</div>)}</div> : block.type === "share" ? <section key={index}><h4 className="text-sm font-semibold">{block.title}</h4>{block.caption && <p className="text-xs text-muted-foreground">{block.caption}</p>}<div className="mt-2 space-y-1">{block.rows.map((row) => <div key={row.label} className="flex justify-between gap-3 rounded bg-muted/30 px-2 py-1.5 text-xs"><span>{row.label}</span><span className="font-mono">{row.value.toLocaleString()}</span></div>)}</div></section> : block.type === "table" ? <section key={index}><h4 className="mb-2 text-sm font-semibold">{block.title}</h4><div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-xs"><thead className="bg-muted/40"><tr>{block.columns.map((column) => <th key={column} className="px-2 py-2 font-medium">{column}</th>)}</tr></thead><tbody>{block.rows.map((row, rowIndex) => <tr key={rowIndex} className="border-t border-border">{row.map((value, cellIndex) => <td key={cellIndex} className="max-w-64 truncate px-2 py-2">{value ?? "—"}</td>)}</tr>)}</tbody></table></div></section> : block.type === "stat" ? <section key={index}><h4 className="text-sm font-semibold">{block.title}</h4><p className="mt-1 text-xl font-semibold">{block.value}</p>{block.caption && <p className="text-xs text-muted-foreground">{block.caption}</p>}</section> : block.type === "narrative" ? <section key={index}><h4 className="text-sm font-semibold">{block.title}</h4><p className="mt-1 whitespace-pre-wrap text-xs leading-relaxed">{block.text}</p></section> : <p key={index} className="border-t border-border pt-3 text-xs text-muted-foreground">{block.text}</p>)}
    {document.method && <p className="border-t border-border pt-3 text-[10px] text-muted-foreground">{document.method}</p>}
  </article>
}
